"""initial_schema

Revision ID: 56ac57a55b24
Revises: 
Create Date: 2026-03-20 12:29:54.414836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ac57a55b24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stations_fetched', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('franchise',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('marker_url', sa.String(length=500), nullable=True),
    sa.Column('marker_hover_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fuel_type',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('long_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('code')
    )
    op.create_table('station',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('open_hours', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_type.pk'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.pk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_snapshot')
    op.drop_table('station')
    op.drop_table('fuel_type')
    op.drop_table('franchise')
    op.drop_table('fetch_log')
    # ### end Alembic commands ###
